### ISSUE TITLE
Change notation in reveal.js

### ISSUE THREAD

**Issue by Phyks** [frederickf/presentable#3]
Hi,

To be more consistent with the reveal.js base slide numerotation (in the lower right corner), wouldn't it be better to write slide numbers as `indexh - indexv` instead of `indexh/indexv` ?

Plus, personnally, I find the first one to be more readable.

Thanks

**Comment by Phyks** [comment]
Any news on this? Thanks!

**Comment by frederickf** [comment]
I just published a new version with an option for this. See https://github.com/frederickf/presentable#pagedivider

**Comment by Phyks** [comment]
Awesome! Thanks!
